# Generated by Django 3.2.9 on 2021-11-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_avialable',
            new_name='is_available',
        ),
    ]
